// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package service_user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DropUserByIDResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropUserByIDResponse) Reset()         { *m = DropUserByIDResponse{} }
func (m *DropUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DropUserByIDResponse) ProtoMessage()    {}
func (*DropUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *DropUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropUserByIDResponse.Unmarshal(m, b)
}
func (m *DropUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *DropUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropUserByIDResponse.Merge(m, src)
}
func (m *DropUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DropUserByIDResponse.Size(m)
}
func (m *DropUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropUserByIDResponse proto.InternalMessageInfo

func (m *DropUserByIDResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DropUserByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropUserByIDRequest) Reset()         { *m = DropUserByIDRequest{} }
func (m *DropUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DropUserByIDRequest) ProtoMessage()    {}
func (*DropUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *DropUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropUserByIDRequest.Unmarshal(m, b)
}
func (m *DropUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *DropUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropUserByIDRequest.Merge(m, src)
}
func (m *DropUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DropUserByIDRequest.Size(m)
}
func (m *DropUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropUserByIDRequest proto.InternalMessageInfo

func (m *DropUserByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserByIDResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIDResponse) Reset()         { *m = UpdateUserByIDResponse{} }
func (m *UpdateUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIDResponse) ProtoMessage()    {}
func (*UpdateUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *UpdateUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIDResponse.Unmarshal(m, b)
}
func (m *UpdateUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIDResponse.Merge(m, src)
}
func (m *UpdateUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIDResponse.Size(m)
}
func (m *UpdateUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIDResponse proto.InternalMessageInfo

func (m *UpdateUserByIDResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateUserByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIDRequest) Reset()         { *m = UpdateUserByIDRequest{} }
func (m *UpdateUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIDRequest) ProtoMessage()    {}
func (*UpdateUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *UpdateUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIDRequest.Unmarshal(m, b)
}
func (m *UpdateUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIDRequest.Merge(m, src)
}
func (m *UpdateUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIDRequest.Size(m)
}
func (m *UpdateUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIDRequest proto.InternalMessageInfo

func (m *UpdateUserByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserByIDRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserByIDRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdateUserByIDRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserByIDRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GetUserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailRequest) Reset()         { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()    {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *GetUserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailRequest.Unmarshal(m, b)
}
func (m *GetUserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailRequest.Merge(m, src)
}
func (m *GetUserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailRequest.Size(m)
}
func (m *GetUserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailRequest proto.InternalMessageInfo

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Rating               int32    `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailResponse) Reset()         { *m = GetUserByEmailResponse{} }
func (m *GetUserByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponse) ProtoMessage()    {}
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *GetUserByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponse.Unmarshal(m, b)
}
func (m *GetUserByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponse.Merge(m, src)
}
func (m *GetUserByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponse.Size(m)
}
func (m *GetUserByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponse proto.InternalMessageInfo

func (m *GetUserByEmailResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserByEmailResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByEmailResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserByEmailResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserByEmailResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserByEmailResponse) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type GetUserByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIDRequest) Reset()         { *m = GetUserByIDRequest{} }
func (m *GetUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDRequest) ProtoMessage()    {}
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *GetUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDRequest.Unmarshal(m, b)
}
func (m *GetUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDRequest.Merge(m, src)
}
func (m *GetUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDRequest.Size(m)
}
func (m *GetUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDRequest proto.InternalMessageInfo

func (m *GetUserByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserByIDResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Rating               int32    `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIDResponse) Reset()         { *m = GetUserByIDResponse{} }
func (m *GetUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDResponse) ProtoMessage()    {}
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *GetUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDResponse.Unmarshal(m, b)
}
func (m *GetUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDResponse.Merge(m, src)
}
func (m *GetUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDResponse.Size(m)
}
func (m *GetUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDResponse proto.InternalMessageInfo

func (m *GetUserByIDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserByIDResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByIDResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserByIDResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserByIDResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserByIDResponse) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{8}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{9}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUsersByPaginationRequest struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              string   `protobuf:"bytes,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByPaginationRequest) Reset()         { *m = GetUsersByPaginationRequest{} }
func (m *GetUsersByPaginationRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersByPaginationRequest) ProtoMessage()    {}
func (*GetUsersByPaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{10}
}

func (m *GetUsersByPaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByPaginationRequest.Unmarshal(m, b)
}
func (m *GetUsersByPaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByPaginationRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersByPaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByPaginationRequest.Merge(m, src)
}
func (m *GetUsersByPaginationRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersByPaginationRequest.Size(m)
}
func (m *GetUsersByPaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByPaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByPaginationRequest proto.InternalMessageInfo

func (m *GetUsersByPaginationRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *GetUsersByPaginationRequest) GetPerPage() string {
	if m != nil {
		return m.PerPage
	}
	return ""
}

type GetUsersByPaginationResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 string   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              string   `protobuf:"bytes,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalUsers           int32    `protobuf:"varint,4,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByPaginationResponse) Reset()         { *m = GetUsersByPaginationResponse{} }
func (m *GetUsersByPaginationResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersByPaginationResponse) ProtoMessage()    {}
func (*GetUsersByPaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{11}
}

func (m *GetUsersByPaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByPaginationResponse.Unmarshal(m, b)
}
func (m *GetUsersByPaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByPaginationResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersByPaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByPaginationResponse.Merge(m, src)
}
func (m *GetUsersByPaginationResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersByPaginationResponse.Size(m)
}
func (m *GetUsersByPaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByPaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByPaginationResponse proto.InternalMessageInfo

func (m *GetUsersByPaginationResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetUsersByPaginationResponse) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *GetUsersByPaginationResponse) GetPerPage() string {
	if m != nil {
		return m.PerPage
	}
	return ""
}

func (m *GetUsersByPaginationResponse) GetTotalUsers() int32 {
	if m != nil {
		return m.TotalUsers
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Rating               int32    `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterType((*DropUserByIDResponse)(nil), "service_user.DropUserByIDResponse")
	proto.RegisterType((*DropUserByIDRequest)(nil), "service_user.DropUserByIDRequest")
	proto.RegisterType((*UpdateUserByIDResponse)(nil), "service_user.UpdateUserByIDResponse")
	proto.RegisterType((*UpdateUserByIDRequest)(nil), "service_user.UpdateUserByIDRequest")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "service_user.GetUserByEmailRequest")
	proto.RegisterType((*GetUserByEmailResponse)(nil), "service_user.GetUserByEmailResponse")
	proto.RegisterType((*GetUserByIDRequest)(nil), "service_user.GetUserByIDRequest")
	proto.RegisterType((*GetUserByIDResponse)(nil), "service_user.GetUserByIDResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "service_user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "service_user.CreateUserResponse")
	proto.RegisterType((*GetUsersByPaginationRequest)(nil), "service_user.GetUsersByPaginationRequest")
	proto.RegisterType((*GetUsersByPaginationResponse)(nil), "service_user.GetUsersByPaginationResponse")
	proto.RegisterType((*User)(nil), "service_user.User")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0x4e, 0x9a, 0x4c, 0xaa, 0x4a, 0x4c, 0xd3, 0x10, 0x1c, 0x50, 0xcd, 0x52, 0xa4,
	0x80, 0x54, 0x1f, 0xca, 0x1f, 0x94, 0x22, 0x54, 0x09, 0x41, 0x65, 0x94, 0x13, 0x87, 0x68, 0xc1,
	0x4b, 0x64, 0xc9, 0xb1, 0xcd, 0xee, 0x06, 0xd4, 0x1f, 0x41, 0x5c, 0xf8, 0x03, 0x24, 0xa4, 0x7e,
	0x21, 0xf2, 0x7a, 0x9d, 0xd8, 0xae, 0x6d, 0x71, 0x6b, 0x6f, 0x9e, 0x9d, 0x37, 0x6f, 0xde, 0xcc,
	0xac, 0x77, 0x00, 0x37, 0x92, 0x8b, 0xa5, 0xe4, 0xe2, 0x7b, 0xf0, 0x85, 0xbb, 0x89, 0x88, 0x55,
	0x8c, 0xfb, 0xc6, 0x5c, 0xa6, 0x3e, 0xea, 0xc2, 0xf8, 0x42, 0xc4, 0xc9, 0x42, 0x72, 0x71, 0x7e,
	0x7d, 0x79, 0xe1, 0x71, 0x99, 0xc4, 0x91, 0xe4, 0x38, 0x81, 0xbe, 0xe0, 0x72, 0x13, 0xaa, 0x29,
	0x71, 0xc8, 0x7c, 0xe8, 0x19, 0x8b, 0x3e, 0x87, 0xc3, 0x32, 0xfe, 0xdb, 0x86, 0x4b, 0x85, 0x07,
	0xd0, 0x09, 0x7c, 0x03, 0xed, 0x04, 0x3e, 0x75, 0x61, 0xb2, 0x48, 0x7c, 0xa6, 0xf8, 0x2d, 0xe2,
	0x31, 0xf4, 0xf8, 0x9a, 0x05, 0xa1, 0x01, 0x67, 0x06, 0xfd, 0x49, 0xe0, 0xa8, 0x1a, 0x50, 0xcb,
	0xbc, 0x8b, 0xef, 0x14, 0xe2, 0x71, 0x06, 0x43, 0x5d, 0x6a, 0xc4, 0xd6, 0x7c, 0xda, 0xd5, 0x9e,
	0x41, 0x7a, 0xf0, 0x9e, 0xad, 0x39, 0x3e, 0x01, 0xf8, 0x1a, 0x08, 0xa9, 0x32, 0xaf, 0xa5, 0xbd,
	0x43, 0x7d, 0xa2, 0xdd, 0x33, 0x18, 0x86, 0x2c, 0xf7, 0xf6, 0xb2, 0xd8, 0xf4, 0x20, 0x75, 0xd2,
	0x53, 0x38, 0x7a, 0xcb, 0x55, 0x26, 0xea, 0x4d, 0x9a, 0x2a, 0xd7, 0x55, 0x5f, 0xc7, 0x5f, 0x02,
	0x93, 0x2a, 0xde, 0x14, 0x7e, 0xb7, 0x85, 0xe8, 0x81, 0x32, 0x15, 0x44, 0xab, 0x69, 0xdf, 0x21,
	0xf3, 0x9e, 0x67, 0x2c, 0x7a, 0x02, 0xb8, 0x15, 0xdc, 0x3c, 0xcf, 0x3f, 0x04, 0x0e, 0x4b, 0xb0,
	0xfb, 0x5d, 0xd4, 0x0d, 0x81, 0x07, 0xaf, 0x05, 0x37, 0xd7, 0xa9, 0x75, 0x64, 0x65, 0x71, 0x9d,
	0x56, 0x71, 0xdd, 0x56, 0x71, 0x56, 0x45, 0x9c, 0x0d, 0x83, 0x84, 0x49, 0xf9, 0x23, 0x16, 0x7e,
	0x2e, 0x3c, 0xb7, 0x11, 0xc1, 0x12, 0x71, 0xc8, 0xb5, 0xec, 0xa1, 0xa7, 0xbf, 0xe9, 0x29, 0x60,
	0x51, 0xb3, 0xe9, 0xf0, 0x43, 0xd8, 0xd3, 0xf2, 0xb6, 0x6d, 0xee, 0xa7, 0xe6, 0xa5, 0x4f, 0xdf,
	0xc1, 0xcc, 0x4c, 0x44, 0x9e, 0x5f, 0x5f, 0xb1, 0x55, 0x10, 0x31, 0x15, 0xc4, 0x51, 0x5e, 0x2c,
	0x82, 0x95, 0xb0, 0x15, 0x37, 0x41, 0xfa, 0x1b, 0x1f, 0xc1, 0x20, 0xe1, 0x62, 0xa9, 0xcf, 0xb3,
	0x4a, 0xf7, 0x12, 0x2e, 0xae, 0xd8, 0x8a, 0xd3, 0x5f, 0x04, 0x1e, 0xd7, 0xd3, 0x19, 0x1d, 0x73,
	0xe8, 0xa5, 0x89, 0xe5, 0x94, 0x38, 0xdd, 0xf9, 0xe8, 0x0c, 0xdd, 0xe2, 0x33, 0xe2, 0x6a, 0xc9,
	0x19, 0x60, 0x9b, 0xb9, 0xd3, 0x90, 0xb9, 0x5b, 0xca, 0x8c, 0xc7, 0x30, 0x52, 0xb1, 0x62, 0xe1,
	0x32, 0xa3, 0xb7, 0xf4, 0x20, 0x41, 0x1f, 0x69, 0x35, 0xf4, 0x37, 0x01, 0x2b, 0xfd, 0xba, 0xa7,
	0x97, 0xed, 0xec, 0xc6, 0x82, 0x51, 0xaa, 0xef, 0x63, 0xd6, 0x10, 0xfc, 0x00, 0xb0, 0x9b, 0x23,
	0x1e, 0x97, 0x1b, 0x75, 0xeb, 0x56, 0xda, 0x4e, 0x33, 0xc0, 0xb4, 0x7e, 0x0d, 0xe3, 0xba, 0xd1,
	0xe0, 0x8b, 0x72, 0x64, 0xcb, 0x6d, 0xb0, 0x5f, 0xfe, 0x0f, 0xd4, 0xa4, 0xf3, 0x60, 0xb4, 0xfb,
	0xd5, 0x7d, 0x74, 0x6a, 0x43, 0x0b, 0x8f, 0x85, 0xfd, 0xb4, 0x05, 0x61, 0x38, 0x3f, 0xc1, 0x41,
	0xf9, 0x59, 0xc4, 0x67, 0x0d, 0x41, 0xc5, 0x47, 0xd6, 0x3e, 0x69, 0x07, 0xed, 0xc8, 0xcb, 0xbb,
	0xa3, 0x4a, 0x5e, 0xbb, 0x59, 0xaa, 0xe4, 0x0d, 0xfb, 0x6a, 0x01, 0xfb, 0x85, 0x85, 0xe7, 0x63,
	0xa5, 0xd8, 0x9a, 0x65, 0x68, 0xd3, 0x36, 0x48, 0x46, 0xfb, 0xb9, 0xaf, 0x97, 0xf1, 0xab, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x1c, 0x16, 0x89, 0xa2, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUsersByPagination(ctx context.Context, in *GetUsersByPaginationRequest, opts ...grpc.CallOption) (*GetUsersByPaginationResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error)
	UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error)
	DropUserById(ctx context.Context, in *DropUserByIDRequest, opts ...grpc.CallOption) (*DropUserByIDResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsersByPagination(ctx context.Context, in *GetUsersByPaginationRequest, opts ...grpc.CallOption) (*GetUsersByPaginationResponse, error) {
	out := new(GetUsersByPaginationResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/GetUsersByPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error) {
	out := new(GetUserByIDResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error) {
	out := new(GetUserByEmailResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/GetUserByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error) {
	out := new(UpdateUserByIDResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/UpdateUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DropUserById(ctx context.Context, in *DropUserByIDRequest, opts ...grpc.CallOption) (*DropUserByIDResponse, error) {
	out := new(DropUserByIDResponse)
	err := c.cc.Invoke(ctx, "/service_user.UserService/DropUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUsersByPagination(context.Context, *GetUsersByPaginationRequest) (*GetUsersByPaginationResponse, error)
	GetUserById(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error)
	UpdateUserByID(context.Context, *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error)
	DropUserById(context.Context, *DropUserByIDRequest) (*DropUserByIDResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUsersByPagination(ctx context.Context, req *GetUsersByPaginationRequest) (*GetUsersByPaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByPagination not implemented")
}
func (*UnimplementedUserServiceServer) GetUserById(ctx context.Context, req *GetUserByIDRequest) (*GetUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByEmail(ctx context.Context, req *GetUserByEmailRequest) (*GetUserByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUserByID(ctx context.Context, req *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserByID not implemented")
}
func (*UnimplementedUserServiceServer) DropUserById(ctx context.Context, req *DropUserByIDRequest) (*DropUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropUserById not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsersByPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsersByPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/GetUsersByPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsersByPagination(ctx, req.(*GetUsersByPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/UpdateUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserByID(ctx, req.(*UpdateUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DropUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DropUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_user.UserService/DropUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DropUserById(ctx, req.(*DropUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service_user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUsersByPagination",
			Handler:    _UserService_GetUsersByPagination_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserService_GetUserByEmail_Handler,
		},
		{
			MethodName: "UpdateUserByID",
			Handler:    _UserService_UpdateUserByID_Handler,
		},
		{
			MethodName: "DropUserById",
			Handler:    _UserService_DropUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
